version: '3'
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params"
            - "./:/var/www/html:cached"
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:7.3.10
        restart: always
        volumes:
            - "/opcache"
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html:cached"
            - "./etc/config/db.php:/var/www/html/config/db.php"
            - "./etc/config/db_console.php:/var/www/html/config/db_console.php"
    composer:
        image: "composer"
        volumes:
            - "./:/app"
        command: install
    compass:
        image: "dockerwest/compass"
        volumes:
          - "./:/cssapp"
        command: compass watch
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=workshop_mysql
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:5
        container_name: workshop_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=workshop
            - MYSQL_ROOT_PASSWORD=verysecret
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql:cached"
            - "./etc/sql:/docker-entrypoint-initdb.d/"
            - "./etc/mysql/sqlmode.cnf:/etc/mysql/conf.d/sqlmode.cnf"