version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8080:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=workshop_Project_mysql
    restart: always
    depends_on:
        - mysqldb
  mysqldb:
    image: mysql:5
    container_name: workshop_project_mysql
    restart: always
    environment:
        - MYSQL_DATABASE=workshop_project
        - MYSQL_ROOT_PASSWORD=verysecret
    ports:
        - "8989:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql:cached"
        - "./etc/sql:/docker-entrypoint-initdb.d/"
        - "./etc/mysql/sqlmode.cnf:/etc/mysql/conf.d/sqlmode.cnf"
